services:
  db:
    image: postgres
    env_file: .env-postgres
    restart: always
    ports:
      - 8432:5432
    volumes:
      - devops-demo-db:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    restart: always
    depends_on:
      - db
    links:
      - db:dbserver

volumes:
  devops-demo-db:
